### ISSUE TITLE
Example application to OCR yiddish handwritten letter is not able to successfully execute

### ISSUE THREAD

**Issue by gedkott** [Lotemn102/HebHTR#2]
Hi Lotem,

I have been trying to use this project to OCR a handwritten letter in yiddish - we are hoping that once we can read the text better, we might be able to translate it. 
I cloned this project and https://github.com/githubharald/CTCWordBeamSearch. I built CTCWordBeamSearch according to their docs and that worked perfectly. 
My entire set of changes is available by viewing: https://github.com/Lotemn102/HebHTR/compare/master...gedkott:yiddish-ocr?expand=1 
I didn't open a PR to avoid creating noise for you since this is more of an application (with some portions, e.g. requirements.txt, .python-version potentially desired upstream if you'd like). 
Additionally, I am running Ubuntu 18.04.6 LTS, 64 bit OS, with 15.3 GiB RAM, Intel® UHD Graphics (CML GT2), and Intel® Core™ i7-10710U CPU @ 1.10GHz × 12. 

When I attempted to run a program using your project:
```
from HebHTR import *

# Create new HebHTR object.
img = HebHTR('./yiddish.png')

# Infer words from image.
text = img.imgToWord(iterations=5, decoder_type='word_beam')
```
I ran into several issues.

1. the version of tensorflow required according to the README.md appears to be only available when running python 2.7.18 (or lower presumably). I added a requirements.txt file with the following:
```
opencv-python == 4.2.0.32
tensorflow == 1.12.0
numpy == 1.16.4
```
After some experimentation, I found that these were the best versions of each dependency needed. I am happy to supply the requirements.txt back to this project if you'd like. 

2. python would crash when reading the data files because of invalid encoding:
```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    text = img.imgToWord(iterations=5, decoder_type='word_beam')
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/HebHTR.py", line 14, in imgToWord
    model = getModel(decoder_type=decoder_type)
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/predictWord.py", line 27, in getModel
    mustRestore=True)
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/Model.py", line 38, in __init__
    self.setupCTC()
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/Model.py", line 155, in setupCTC
    corpus.encode('utf8'), chars.encode('utf8'),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd7 in position 0: ordinal not in range(128)
```
This was resolved by defaulting all encodings to utf-8 during the main.py script execution:
```
# coding: utf-8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

3. Next, the script would fail due to check-pointing with tensorflow. An excerpt of the stacktrace:
```
InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [1,1,512,96] rhs shape= [1,1,512,69]
	 [[node save/Assign_16 (defined at /home/gedalia-kott/hebrew-ocr-projects/HebHTR/Model.py:161)  = Assign[T=DT_FLOAT, _class=["loc:@Variable_5"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Variable_5/RMSProp, save/RestoreV2:16)]]
```
I can provide more detail if it helps, but this was resolved by deleting the checkpoint, snapshot, and accuracy files from the model directory.

4. Next, the script would fail when executing:
```
if self.mustRestore and not latestSnapshot:
            raise Exception('No saved model found in: ' + modelDir)
```
This was resolved by modifying the invocation in predictWord.py from:
```
model = Model(open(FilePaths.fnCharList).read(), decoderType,
                  mustRestore=False)
```
to 
```
model = Model(open(FilePaths.fnCharList).read(), decoderType,
                  mustRestore=True)
```
I believe this will force the model files to be recreated if the previous ones are not compatible with my environment.

5. Last, I am not able to run the script because in processFunctions.py in the method preprocessImageForPrediction, I am seeing that the dimensions of my PNG image is a tuple with three elements (dimension of 3) and the function is assuming the image will be a tuple of dimension two resulting in the following:
```
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    text = img.imgToWord(iterations=5, decoder_type='word_beam')
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/HebHTR.py", line 15, in imgToWord
    transcribed_words.extend(predictWord(self.original_img, model))
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/predictWord.py", line 32, in predictWord
    return infer(model, image)
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/predictWord.py", line 15, in infer
    img = preprocessImageForPrediction(image, Model.imgSize)
  File "/home/gedalia-kott/hebrew-ocr-projects/HebHTR/processFunctions.py", line 20, in preprocessImageForPrediction
    target[0:newSize[1], 0:newSize[0]] = img
ValueError: could not broadcast input array from shape (32,26,3) into shape (32,26)
```
I am not sure how to proceed from here.

Would love to get your input on how I can update the project to work for me. I am happy to discuss compensation for your time and effort helping me as well. 

Gedalia Kott

**Comment by Lotemn102** [comment]
Hi Gedalia,

How are you? Thanks for reaching out.

The code for this project is not maintained, and it's been a while since the last time i have used it. 
Anyway, I will try my best to help you and hope that we can make it work on your machine.

As for your question - Your input images have 3 channels, i.e they are RGB images. The network was trained on binary images i.e images with 1 channel.
Try to convert your image to grayscale or binary. That will result you with input of shape (32,26,1). I don't remember if that's the case, but TF might not automatically convert tensors of shape (W,H,1) into tensors of shape (W,H), so you might want to use numpy.squeeze() in order to get input of shape (32,26) after the grayscaling.

Let me know if that helps,
Lotem

**Comment by gedkott** [comment]
Hi Lotem,
Appreciate your response and help! 
I did as you said and it pushed me forward, but ultimately, the program resulted in a core dump which isn't easy to trace so I have discontinued my project attempting to use this tool. 
Thanks again and all the best!
Gedalia Kott
