### ISSUE TITLE
Hello can i use this inside android app i'm building?

### ISSUE THREAD

**Issue by NiroDev26** [Lotemn102/HebHTR#7]
Hello,

I want to use this module to extract hand written hebrew text from images taken within an android phone,
for an android app i'm builiding.

would love some help and\or directions on how to use, if possible at all.

thanks,

**Comment by Lotemn102** [comment]
Hi,

I'm not familiar with AI deployment for Android or iOS, so unfortunately I won't be able to help you with that.
It also depends on whether you want to apply the inference on-prem or on cloud.
If you intend to use it on-prem, I suspect you'll need to reduce the model's size for that. Check out [quantization](https://leimao.github.io/article/Neural-Networks-Quantization/) or [decomposition](https://machinelearningmastery.com/introduction-to-matrix-decompositions-for-machine-learning/) methods. 

Lotem
